---
- hosts: localhost
  connection: local
  collections:
    - azure.azcollections
  
  #Set Variables
  vars:
    wth_location: eastus2
    wth_rg_name: ansible-wth-rg
    wth_ssh_nsg: ansible_wth_nsg
    wth_vm_nsg_list: 
      - name: allow-ssh
        access: Allow
        protocol: Tcp
        direction: Inbound
        priority: 1000
        port: 22 
        source_address_prefix: Internet
      - name: allow-http
        access: Allow
        protocol: Tcp
        direction: Inbound
        priority: 1020
        port: 80 
        source_address_prefix: Internet
    
  # Variables for VM Creation (VMName, RSA Key Path)

    admin_pub_path: "~/.ssh/id_rsa.pub"
    wth_vm_name: anlinuxvm
    wth_admin_user: azureuser

  # Variables for Availability Set Additions
    wth_availabilityset_name: wthAnsibleASet
    wth_vm_root_name: "{{wth_vm_name}}-vm"
    wth_nic_root_name: "{{wth_vm_name}}-nic"
    wth_instance_num: 2

  tasks:
  # Create a resource group in a local region

  - name: Create a resource named ansible-wth-rg 
    azure_rm_resourcegroup:
      name: "{{ wth_rg_name }}"
      location: "{{ wth_location }}"

  # Create Virtual Network

  - name: "Create Virtual Network"
    azure_rm_virtualnetwork:
      name: wthVnet
      resource_group: "{{ wth_rg_name }}"
      address_prefixes_cidr:
        - "10.2.0.0/16"
  
  # Create Subnet

  - name: "Create Subnet"
    azure_rm_subnet:
      name: default
      virtual_network_name: wthVnet
      resource_group: "{{ wth_rg_name }}"
      address_prefix_cidr: "10.2.1.0/24"

  # Create NSG for ssh and http

  - name: Create Network Security Group that allows ssh
    azure_rm_securitygroup:
       resource_group: "{{ wth_rg_name }}"
       name: "{{ wth_ssh_nsg }}"
       rules:
         - name: "{{ item.name }}"
           protocol: "{{ item.protocol }}"
           source_address_prefix: "{{ item.source_address_prefix }}"
           destination_port_range: "{{ item.port }}"
           access: "{{ item.access }}"
           priority: "{{ item.priority }}"
           direction: "{{ item.direction }}"
    loop: "{{ wth_vm_nsg_list }}"
    
  # Create availability set 
 
  - name: "Create Availability Set"
    azure_rm_availabilityset:
      name: "{ {wth_availabilityset_name }}"
      location: "{{ wth_location }}"
      resource_group: "{{ wth_rg_name }}"
      sku: Aligned
 
 
  # Create Public IP Address for VM

  - name: Create public IP address
    azure_rm_publicipaddress:
      resource_group: "{{ wth_rg_name }}"
      allocation_method: Static
      name: ansible-pip
  
  
  # Create Network Interface Card for VM

  - name: Create virtual network inteface card
    azure_rm_networkinterface:
        resource_group: "{{ wth_rg_name }}"
        name: ansible-VM-nic
        virtual_network: wthVnet
        subnet: default
        public_ip_name: ansible-pip
        security_group: "{{ wth_ssh_nsg }}"

  # Create VM with Data Disk

  - name: Create VM
    azure_rm_virtualmachine:
        resource_group: "{{ wth_rg_name }}"
        name: "{{ wth_vm_name }}"
        vm_size: Standard_DS1_v2
        admin_username: azureuser
        ssh_password_enabled: false
        managed_disk_type: Premium_LRS
        ssh_public_keys:
        - path: /home/azureuser/.ssh/authorized_keys
          key_data: "{{lookup('file', '{{admin_pub_path}}') }}"
        network_interfaces: ansible-VM-nic
        image:
          offer: CentOS
          publisher: OpenLogic
          sku: '8.0'
          version: latest
        data_disks:
        - lun: 0
          disk_size_gb: 128
          managed_disk_type: Premium_LRS
