---
- hosts: all
  tasks:
    - name: Upgrade all packages
      yum:
        name: '*'
        state: latest
    - name: Install epel-release
      yum:
        name: epel-release
        state: latest
    - name: Install NGINX
      yum:
        name: nginx
        state: latest
    - name: Ensure NGINX is set to running state
      service:
        name: nginx
        state: started
    - name: Add html page for verification
      shell: echo '\<center>\<h1>Welcome to What The Hack{{":"}} IaC Ansible Challenges</h1><br/></center>' > /usr/share/nginx/html/wth.html
      
        